version: '3.8'

services:
  jupyterlab:
    image: jupyter/tensorflow-notebook:54462805efcb
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '8888:8888'
    volumes:
      - ./:/home/jovyan/work
